### PR TITLE
Initial xspectra parser

### PR DESCRIPTION
**Pull request by ladinesa**

### CODE REVIEW

**Comment by JosePizarro3** [comment]
I will be pushing some changes tomorrow, then you can review them, and in the meantime I will be working on your suggestions in the OCEAN parser 🙂 

Then tomorrow afternoon we can set up the workflow for DFT+CoreHole/BSE

**Comment by JosePizarro3** [comment]
@ladinesa can you please check my changes? I changed myself from reviewer to assignee.

**Comment by ondracka** [comment]
> Then tomorrow afternoon we can set up the workflow for DFT+CoreHole/BSE

Please CC me when you have something working for the corehole workflow. I have a lot of core-hole calculations in NOMAD, both from Wien2k (all electrons with full core holes as well as some fractional coreholes) and from OpenMX, so I would be interested in what is needed (on the OpenMX and Wien2k parser side) to get such calculations recognized.

**Comment by JosePizarro3** [comment]
Ok, I pushed some changes.

**Comment by JosePizarro3** [comment]
> > Then tomorrow afternoon we can set up the workflow for DFT+CoreHole/BSE
> 
> Please CC me when you have something working for the corehole workflow. I have a lot of core-hole calculations in NOMAD, both from Wien2k (all electrons with full core holes as well as some fractional coreholes) and from OpenMX, so I would be interested in what is needed (on the OpenMX and Wien2k parser side) to get such calculations recognized.

@ondracka that sounds very nice! Can you write me to my email (jose.pizarro@physik.hu-berlin.de) and we discuss the details in there?

**Comment by JosePizarro3** [comment]
@ladinesa ok I tested it, it works good. Please, merge at will.

**Pull request merged**
